// nazionalita.ts — le nazionalità del database, TRADOTTE IN ITALIANO.
//
// Il database usa i nomi inglesi delle federazioni ("Germany", "Türkiye"…):
// vanno bene come CHIAVI (il compositore dei volti e i filtri li usano così),
// ma sullo schermo il gioco parla italiano (piano di progetto, M11).
// Questa mappa copre tutte le nazionalità presenti nel database; per
// sicurezza, un nome sconosciuto viene mostrato com'è.

const TRADUZIONI: Record<string, string> = {
  Albania: 'Albania',
  Algeria: 'Algeria',
  Andorra: 'Andorra',
  Angola: 'Angola',
  Argentina: 'Argentina',
  Armenia: 'Armenia',
  Australia: 'Australia',
  Austria: 'Austria',
  Azerbaijan: 'Azerbaigian',
  Bangladesh: 'Bangladesh',
  Belgium: 'Belgio',
  Benin: 'Benin',
  'Bosnia and Herzegovina': 'Bosnia ed Erzegovina',
  Brazil: 'Brasile',
  Bulgaria: 'Bulgaria',
  'Burkina Faso': 'Burkina Faso',
  Burundi: 'Burundi',
  'Cabo Verde': 'Capo Verde',
  Cameroon: 'Camerun',
  Canada: 'Canada',
  'Central African Republic': 'Rep. Centrafricana',
  Chile: 'Cile',
  Colombia: 'Colombia',
  Comoros: 'Comore',
  Congo: 'Congo',
  'Congo DR': 'RD del Congo',
  Croatia: 'Croazia',
  Cuba: 'Cuba',
  Curacao: 'Curaçao',
  Cyprus: 'Cipro',
  'Czech Republic': 'Rep. Ceca',
  Czechia: 'Rep. Ceca',
  "Côte d'Ivoire": "Costa d'Avorio",
  Denmark: 'Danimarca',
  'Dominican Republic': 'Rep. Dominicana',
  Ecuador: 'Ecuador',
  Egypt: 'Egitto',
  England: 'Inghilterra',
  'Equatorial Guinea': 'Guinea Equatoriale',
  Estonia: 'Estonia',
  Finland: 'Finlandia',
  France: 'Francia',
  Gabon: 'Gabon',
  Gambia: 'Gambia',
  Georgia: 'Georgia',
  Germany: 'Germania',
  Ghana: 'Ghana',
  Greece: 'Grecia',
  Guinea: 'Guinea',
  'Guinea-Bissau': 'Guinea-Bissau',
  Haiti: 'Haiti',
  Honduras: 'Honduras',
  Hungary: 'Ungheria',
  Iceland: 'Islanda',
  Indonesia: 'Indonesia',
  Iran: 'Iran',
  Israel: 'Israele',
  Italy: 'Italia',
  'Ivory Coast': "Costa d'Avorio",
  Jamaica: 'Giamaica',
  Japan: 'Giappone',
  Jordan: 'Giordania',
  Kenya: 'Kenya',
  'Korea Republic': 'Corea del Sud',
  Kosovo: 'Kosovo',
  Latvia: 'Lettonia',
  Lebanon: 'Libano',
  Libya: 'Libia',
  Lithuania: 'Lituania',
  Luxembourg: 'Lussemburgo',
  Madagascar: 'Madagascar',
  Malaysia: 'Malesia',
  Mali: 'Mali',
  Malta: 'Malta',
  Mauritania: 'Mauritania',
  Mexico: 'Messico',
  Moldova: 'Moldavia',
  Montenegro: 'Montenegro',
  Morocco: 'Marocco',
  Mozambique: 'Mozambico',
  Namibia: 'Namibia',
  Netherlands: 'Olanda',
  'New Zealand': 'Nuova Zelanda',
  Niger: 'Niger',
  Nigeria: 'Nigeria',
  'North Macedonia': 'Macedonia del Nord',
  'Northern Ireland': 'Irlanda del Nord',
  Norway: 'Norvegia',
  Panama: 'Panama',
  Paraguay: 'Paraguay',
  Peru: 'Perù',
  Philippines: 'Filippine',
  Poland: 'Polonia',
  Portugal: 'Portogallo',
  Qatar: 'Qatar',
  'Republic of Ireland': 'Irlanda',
  Romania: 'Romania',
  Russia: 'Russia',
  'Saudi Arabia': 'Arabia Saudita',
  Scotland: 'Scozia',
  Senegal: 'Senegal',
  Serbia: 'Serbia',
  'Sierra Leone': 'Sierra Leone',
  Slovakia: 'Slovacchia',
  Slovenia: 'Slovenia',
  'South Africa': 'Sudafrica',
  Spain: 'Spagna',
  'Sri Lanka': 'Sri Lanka',
  Suriname: 'Suriname',
  Sweden: 'Svezia',
  Switzerland: 'Svizzera',
  Tanzania: 'Tanzania',
  Thailand: 'Thailandia',
  Togo: 'Togo',
  Tunisia: 'Tunisia',
  'Türkiye': 'Turchia',
  Uganda: 'Uganda',
  Ukraine: 'Ucraina',
  'United Arab Emirates': 'Emirati Arabi',
  'United States': 'Stati Uniti',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Uzbekistan',
  Venezuela: 'Venezuela',
  Wales: 'Galles',
  Zambia: 'Zambia',
  Zimbabwe: 'Zimbabwe',
}

/** Il nome italiano di una nazionalità del DB (o il nome originale se ignota). */
export function nazionalitaInItaliano(nome: string): string {
  return TRADUZIONI[nome] ?? nome
}
